# Data
data:
  root: datasets/MMAD
  output_root: ./output

# Anomaly Detection Model
anomaly:
  model: patchcore  # patchcore | winclip | efficientad

  patchcore:
    backbone: null
    layers: null
    coreset_sampling_ratio: null

  winclip:
    class_name: null
    k_shot: null
    scales: null

  efficientad:
    model_size: null
    teacher_out_channels: null

# Training
training:
  train_batch_size: null
  eval_batch_size: null
  num_workers: null
  max_epochs: null  # null -> model default

# Engine
engine:
  accelerator: cpu  # auto | cpu | gpu | mps # Mac은 cpu 권장 mps 호환성 문제 심함
  enable_progress_bar: false
  logger: false

# Output
output:
  save_json: true
